### ISSUE TITLE
Non-blocking requests by using cqueues

### ISSUE THREAD

**Issue by aleclarson** [daurnimator/lua-http#100]
Please add an example of using `cqueues` to make a request non-blocking, like when using `each_chunk`.

**Comment by aleclarson** [comment]
Also, how can I "wait" for the response headers without blocking?

**Comment by daurnimator** [comment]
Generally, you can just run functions inside of a cqueues managed coroutine and it will "just work".

e.g. 

```lua
local cq = require "cqueues".new()
cq:wrap(function()
     local headers, stream = assert(myrequest:go())
    --etc.
end)

-- Now register cq with your main loop. See https://github.com/wahern/cqueues/wiki/Integrations-with-other-main-loops
```

**Comment by aleclarson** [comment]
Makes sense. Thanks!
