### ISSUE TITLE
Limit byte count when using stream:write_body_from_file

### ISSUE THREAD

**Issue by cafehaine** [daurnimator/lua-http#106]
Hi, Im creating something close to Ownctload/nextcloud in lua, and I'm trying to allow resuming of paused downloads.
The thing is, lua-http can send the end of a file with `stream:write_body_from_file(file, timeout)` by seeking the begining of the file, but there is no way to handle the second "part" of the range header, ie where to stop.
I know I don't really need it for what I want, but it would be great to add a way to stop sending bytes from a file after a certain amount of bytes. This would allow to fully implement the Range header and not just the "resume" part of it.

**Comment by daurnimator** [comment]
How should the API look without an explosion of options?

**Comment by cafehaine** [comment]
for me stream:write_body_from_file(file, timeout, bytes) would do the trick, just allow the user to send a specified amount of bytes, since the start point can be set with file:seek

**Comment by daurnimator** [comment]
> since the start point can be set with file:seek

When there is a retry lua-http seeks back to the sart

------

The issue I'm alluding to is why stop at just bytes to stop at? You could make similar arguments for the block size, a stride between blocks, some sort of encoding conversion, and yes: the start offset.

There's also the API issue that `timeout` should always be the final argument by convention: we'd have to call the new api a new name (as the new argument is also a number and can't be distinguished for overloading).

This is not a "no" to the request, it's just that there is plenty more to it.

**Comment by daurnimator** [comment]
> When there is a retry lua-http seeks back to the sart

Oh. That's in the http.request module. I think you were talking about in a server?

**Comment by RyanSquared** [comment]
> Oh. That's in the http.request module. I think you were talking about in a server?

Looks like it judging by their statement that they want this functionality in the _send_ function rather than _receive_, in which case having an optional argument to the sending function limiting the received amount of bytes.

**Comment by daurnimator** [comment]
> Looks like it judging by their statement that they want this functionality in the send function rather than receive

I understood that. I thought they were talking about uploading a file as a client

**Comment by cafehaine** [comment]
Nope, didn't think about upload since for me upload would be in lan, so low chance of errors during upload.
Sorry If I wasn't clear enough at the time

**Comment by daurnimator** [comment]
Please review #125
