### ISSUE TITLE
websocket:receive(timeout) does not have the normal return value order.

### ISSUE THREAD

**Issue by ardje** [daurnimator/lua-http#107]
Hi,

If I do:
`local cmd,etext,errno=ws:receive(30)`
I have to:
`if cmd == nil then
    if etext == ce.ETIMEDOUT then`

instead of using errno.

Now the `ws:receive()` on timeout just returns whatever cqueues socket:xread returns:
`local first_2, err, errno = sock:xread(2, "b", deadline and (deadline-monotime()))
 if not first_2 then
                        return nil, err, errno
`
So :xread returns errno in err..

**Comment by ardje** [comment]
As a side note: I just wanted to timeout, clearerr, send_ping() and then loop again to keep the stream alive through a proxy. I will now try to use a second coroutine, which should make the code much more simple. I only fear it might interfer with other frames.

**Comment by daurnimator** [comment]
Should be fixed via #110.
