### ISSUE TITLE
http request fails when $http_proxy contains trailing slash

### ISSUE THREAD

**Issue by mischief** [daurnimator/lua-http#108]
hi, my `$http_proxy` is set to `http://127.0.0.1:8118/`. this works fine with all other programs (chromium, curl, ...). http.request asserts when the trailing slash is present. here's a patch to fix it.

```diff
diff --git a/http/request.lua b/http/request.lua
index 3f12a8f..ce1cb88 100644
--- a/http/request.lua
+++ b/http/request.lua
@@ -59,7 +59,7 @@ local function new_from_uri(uri_t, headers)
 		is_connect = headers:get(":method") == "CONNECT"
 	end
 	if is_connect then
-		assert(uri_t.path == nil or uri_t.path == "", "CONNECT requests cannot have a path")
+		assert(uri_t.path == nil or uri_t.path == "" or uri_t.path == "/", "CONNECT requests cannot have a path")
 		assert(uri_t.query == nil, "CONNECT requests cannot have a query")
 		assert(headers:has(":authority"), ":authority required for CONNECT requests")
 	else
```

**Comment by daurnimator** [comment]
I think it might be better to make a special case for this in the env var reading code.

**Comment by daurnimator** [comment]
> I think it might be better to make a special case for this in the env var reading code.

I remembered why the validation code is currently in http.request: I expect people would end up setting the proxy themselves manually for a request, e.g. `myrequest.proxy = "foo.com"`. I guess for this issue we'd want `myrequest.proxy = "http://foo.com/ignore-this-path"` to work as well?

**Comment by mischief** [comment]
thanks!
