### ISSUE TITLE
starttls? Error on Request

### ISSUE THREAD

**Issue by dedayoa** [daurnimator/lua-http#130]
Hello,
My configuration has not changed since I posted https://github.com/daurnimator/lua-http/issues/126.
In the past 24 hours, requests with lua-http have failed. Wrapping req:go() with an assert results in 
`starttls: The name does not resolve for the supplied parameters`
I know this is probably as a result of a change on my web server (which I have no control over), because nothing has changed in my code, but can you provide any guidance on what this error is and how to (hopefully) work around it?

**Comment by daurnimator** [comment]
Closing due to lack of response from OP.
