### ISSUE TITLE
Is this intentional or an error in the example?

### ISSUE THREAD

**Issue by RussellHaley** [daurnimator/lua-http#131]
Hello, 

I am using some of the example code and there are some odd characters in serve_dir.lua: https://github.com/daurnimator/lua-http/blob/master/examples/serve_dir.lua#L128-L130

It also renders oddly on my Debian Jessie (not tested anywhere else).

**Comment by cafehaine** [comment]
It's an emoji, you need to install an emoji font to see it

**Comment by RussellHaley** [comment]
Well, in expedience, I replaced it with the same content as line 26. I'll go download emoji packs from random sites later. Since it's not a bug, I won't bother pushing a patch.
o_O

**Comment by daurnimator** [comment]
yes it is intentional, it's the unicode character 'FILE FOLDER' (U+1F4C1)
https://www.fileformat.info/info/unicode/char/1f4c1/index.htm

If you can't see it then you need to update your system and/or install at least one font from the last 8 years :)

**Comment by RussellHaley** [comment]
Rofl. Okay, the joke really is on me. Sorry @cafehaine I thought you were pulling my leg!
