### ISSUE TITLE
HTTP method must be set in "headers"

### ISSUE THREAD

**Issue by leonardus** [daurnimator/lua-http#133]
It would make more sense to have the HTTP method be a property of the `request` object, rather than set in the request's `headers` object.

Example:
```lua
request = http_request.new_from_uri("http://example.org/post")
request.method = "POST"
request:go()
```

**Comment by daurnimator** [comment]
lua-http follows HTTP2 convention where method is just another HTTP header. 

See https://daurnimator.github.io/lua-http/0.2/#conventions
