### ISSUE TITLE
is there a plan to put lua-http in "OPM Openresty" ecosystem?

### ISSUE THREAD

**Issue by eulhaque** [daurnimator/lua-http#137]
openresty have rolled out their own package manager (opm) which plays really well with OpenResty ecosystem and the use of luarocks have been discouraged. Do you have any plans to put lua-http in "OPM"? 

This will greatly help, specially, openresty still does not support cosockets during the nginx startup phases.

https://opm.openresty.org/

**Comment by daurnimator** [comment]
I have no intention to add it to OPM, I think it forks the already small lua community too much.
