### ISSUE TITLE
websocket:receive() unexpected behavior with a timeout

### ISSUE THREAD

**Issue by Mehgugs** [daurnimator/lua-http#138]
I call receive with a timeout value of `60` seconds. 
My socket receives ETIMEOUT : 
```
Shard-0 has stopped receiving: (ETIMEDOUT "Connection timed out") (close code nil) 0.269sec elapsed
```
The elapsed time here is measuring how much time has elapsed since I called `connect` 

Have I misunderstood the function of the timeout or is this not intended behaviour?

**Comment by daurnimator** [comment]
I think you're running into #89 which was fixed in https://github.com/daurnimator/lua-http/commit/aed86deaaaa65dfbf209b735e79f6328eb08605c#diff-5c28716ac7c4f4327dd318b6659a7242

Are you running 0.2 or master?

**Comment by Mehgugs** [comment]
This build 0.2 from luarocks, I can try from master and see if this fixes the problem. 
```
~# luarocks show http

http 0.2-1 - HTTP library for Lua
```

**Comment by Mehgugs** [comment]
After cloning master and `luarocks make` i can confirm this is fixed, thanks. Will there be a luarocks release in the future with this fix?

**Comment by daurnimator** [comment]
Yes there will be a release soon.
