### ISSUE TITLE
How to handle websocket closure?

### ISSUE THREAD

**Issue by Mehgugs** [daurnimator/lua-http#139]
(I'm using using `scm-0` from `8ab5c30198446bbd8522acef200c1c4b8274328b`)
Websocket closure is difficult to handle correctly, and seems to be ignored somewhat by the websocket client's documented API. I'm using a `repeat <receive code> until frame == nil` loop to get the messages.

```
Websocket close detected (found: 1000) <- Here I check socket.got_close_code
Previous: ("string" 17bytes, binary) <- I print previous msg, op I got from receive
Shard-0 has stopped receiving: ("receive: Broken pipe") (close code 32) 3.402sec elapsed <- EPIPE on next receive before receiving a close result from receive
```
How do write the condition for my loop given that `socket.got_close_code` is an internal value?

**Comment by daurnimator** [comment]
> I'm using a `repeat <receive code> until frame == nil` loop to get the messages.

Could you share the code you're using?
Usually you'd do something like:
```lua
while true do
    local data, err, errno = ws:receive(mytimeout)
    if not data then
        -- there was an error or a close. look at err/errno.
        break
    end
    dostuffwith(data)
end
```

**Comment by Mehgugs** [comment]
I'm using the internal values because the return values are confusing to me, so im going to close this.

**Comment by daurnimator** [comment]
Are you saying that the contents of `code` is `EPIPE` rather than the close code that the other side sent?
