### ISSUE TITLE
Feature Request: Simple way to serialize/output an HTTP request

### ISSUE THREAD

**Issue by RussellHaley** [daurnimator/lua-http#151]
It may just be my use case, but it would be nice to be able to get a string of my http request that I can dump to file prior to sending, especially once https is turned on. I might be able to piece something together from the `http.request:go()` function, but thought I'd mention it. I looked briefly at the `go` function and it seems heavily intertwined with the socket connection (I suspect due to the way an http request is actually sent).

Thanks,
Russ

**Comment by daurnimator** [comment]
Why would you want to dump it to file?

For debugging I mostly use:
  - `headers:dump()`
  - set `SOCKET_DEBUG=1` environment variables

See also #69

**Comment by RussellHaley** [comment]
Works for me! Thanks.
