### ISSUE TITLE
Error on Request: invalid URI

### ISSUE THREAD

**Issue by webr0m** [daurnimator/lua-http#155]
I tried to replicate a simple connection code based on one that I use with lua-curl, however it generates an error when connecting:
```
lua: /usr/local/share/lua/5.1/http/request.lua:50: invalid URI
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/http/request.lua:50: in function 'new_from_uri'
        ./methods.lua:136: in function 'performRequest'
        ./methods.lua:204: in function <./methods.lua:146>
        (tail call): ?
        bot.lua:748: in main chunk
        [C]: ?
```

The code of lua curl is:

```
local curl_context = curl.easy{verbose = config.bot_settings.debug_connections}
function performRequest(url)
	local data = {}

	-- if multithreading is made, this request must be in critical section
	local c = curl_context:setopt_url(url)
		:setopt_ssl_verifypeer(false)
		:setopt_ssl_verifyhost(false)
		:setopt_writefunction(table.insert, data)
		:perform()
--	print(table.concat(data), c:getinfo_response_code())
	
	return table.concat(data), c:getinfo_response_code()
end
```
and the lua-http code is:

```
function performRequest(url)
	local data = {}
	local http_request = require "http.request"
	local headers, stream = assert(http_request.new_from_uri(url):go())
	local body = assert(stream:get_body_as_string())
	if headers:get ":status" ~= "200" then
		print(body)
	end
	table.insert(data, body)
	print(body, tonumber(headers:get ":status"))
	return table.concat(data), tonumber(headers:get ":status")
end
```

The error is only generated when the url contains certain values ​​encoded in json, otherwise it works fine, it is to connect a bot in the telegram api

**Comment by daurnimator** [comment]
> The error is only generated when the url contains certain values ​​encoded in json,

What values? My suspicion is that it's not a valid url but curl accepts it anyway.

**Comment by webr0m** [comment]
This are example URL:

https://api.telegram.org/bot114141415:AAE1PDyouvrIKeLFBKv6gSYfYmOb-39GfwTE/sendMessage?chat_id=-1001095887694&text=%2aBot%20iniciado%2a%0aD%c3%ada%20Thursday%2c%2020%20June%202019%0aHora%2012%3a05%3a46%0a38%20plugins%20le%c3%addos&parse_mode=Markdown&disable_notification=true&disable_web_page_preview=true

https://api.telegram.org/bot114141415:AAE1PDyouvrIKeLFBKv6gSYfYmOb-39GfwTE/getUpdates?timeout=3600&limit=1&allowed_updates=["message","edited_message","callback_query","inline_query","channel_post","chosen_inline_result"]

**Comment by webr0m** [comment]
Ok, I solve this, I just have to escape the url completely to avoid the error.

```
url = require 'socket.url'
url.escape(json.encode(keyboard))
```

Another question, is there any way to skip the verification ssl as it has lua-curl options

```
setopt_ssl_verifypeer (false)
setopt_ssl_verifyhost (false) 
```

**Comment by daurnimator** [comment]
> url = require 'socket.url'

See lua-http's `http.util` module. You probably want either [`dict_to_query`](https://daurnimator.github.io/lua-http/0.3/#http.util.dict_to_query) or [`encodeURIComponent`](https://daurnimator.github.io/lua-http/0.3/#http.util.encodeURIComponent)



>  is there any way to skip the verification ssl as it has lua-curl options

See [`request.ctx`](https://daurnimator.github.io/lua-http/0.3/#http.request.ctx). You would do something like:
```lua
local http_request = require "http.request"
local http_tls = require "http.tls"
local openssl_ctx = require "openssl.ssl.context"

local r = http_request.new_from_uri("http://example.com")
r.ctx = http_tls.new_client_context()
r.ctx:setVerify(openssl_ctx.VERIFY_NONE)
```

See the [luaossl docs](https://github.com/wahern/luaossl/releases/download/rel-20190612/luaossl.pdf) for further options.

**Comment by webr0m** [comment]
oh thanks, this really worked for me and congratulations for this wonderful lib for lua ;)
