### ISSUE TITLE
Add support for SSLKEYLOGFILE or equivalent

### ISSUE THREAD

**Issue by pspacek** [daurnimator/lua-http#160]
Hello,

I think that supporting SSLKEYLOGFILE functionality as seen in NSS/Firefox and GnuTLS would make debugging weird HTTPS problems much simpler.

OpenSSL has support for it already, but it needs small tweaks on the apps side as well:

https://github.com/openssl/openssl/pull/2343
https://github.com/openssl/openssl/commit/4bf73e9f86804cfe98b03accfc2dd7cb98e018d6

**Comment by daurnimator** [comment]
See #57

**Comment by pspacek** [comment]
Sorry about the duplicate, I did not try hard enough.
