### ISSUE TITLE
Installed via luarocks but can't find http

### ISSUE THREAD

**Issue by CptMaumau** [daurnimator/lua-http#161]
Installed on Ubuntu 16 via luarocks but lua can't find the module
![Screen Shot 2019-11-08 at 5 22 57 PM](https://user-images.githubusercontent.com/5366008/68461053-b2472b00-024c-11ea-9256-77563dfcd2a4.png)

**Comment by daurnimator** [comment]
Your luarocks seems misconfigured to install to a place that your lua interpreter is not looking (this is not a lua-http issue)
