### ISSUE TITLE
runtime error: error loading module '_openssl.ssl.context'

### ISSUE THREAD

**Issue by djaneluz** [daurnimator/lua-http#164]
Error at line: require "http.request"

`2020/02/07 19:07:28 [error] 20#20: *6 lua entry thread aborted: runtime error: error loading module '_openssl.ssl.context' from file '/opt/lua_modules/lib/lua/5.1/_openssl.so':`

Any idea?

**Comment by RyanSquared** [comment]
Is that the only error you're given? What happens if you try `require("_openssl.ssl.context")` ?

**Comment by Djane** [comment]
Yes.. this is the only error. I'm actually not using directly this module, the error is triggered at line:
`local request = require "http.request"`

I added the require you suggested, but didn't work as well

**Comment by RyanSquared** [comment]
What's the error that it gives you when you use the line that I've provided? It looks like your error message might have been incomplete and/or missing context as to what actually happened.

**Comment by daurnimator** [comment]
Without more information (an error message; or replication instructions) we can't help further
