### ISSUE TITLE
it is passible to handle keep-alive connections by the library?

### ISSUE THREAD

**Issue by andrejlevkovitch** [daurnimator/lua-http#165]
`http.request` create new connection every call `go` method and close stream. So there is a way to reuse connection several times by `keep-alive`?

**Comment by daurnimator** [comment]
The library supports it for the lower level `connection` and `stream` apis, but not for the high level `request` object. The hard bit is knowing if an existing connection is suitable for a new request (need to check dns, certificates, any SSL settings, http version selection, etc. its quite a long list)

See https://github.com/daurnimator/lua-http/pull/121
