### ISSUE TITLE
get_body_as_string() returns newlines.

### ISSUE THREAD

**Issue by Meaxis** [daurnimator/lua-http#167]
When using the function get_body_as_string(), the result is returned with several newlines.
```




[body]
```

**Comment by daurnimator** [comment]
This would only occur if your server is sending the additional new lines... in which case, it probably wants you to have them.

**Comment by Meaxis** [comment]
I think you’re right, will update you.



	
		
			
				
			
		
		
			
				L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
				www.avast.com

**Comment by Meaxis** [comment]
Yep. That was my server. Sorry :/
