### ISSUE TITLE
Installation on http.lua etc. into a Lua app on an iPad - how to ?

### ISSUE THREAD

**Issue by nodecentral** [daurnimator/lua-http#176]
Hi

I’m looking to use http.socket on an iPad Lua app, and I’m told I need to install the module and any dependencies into a particular folder. What is the best way to download all the required Lua files (e.g http.lua ) so I can upload them ?

Many thanks !!

**Comment by daurnimator** [comment]
I don't think you would be able to install the dependencies (luaossl, cqueues) in an ipad app (due to Apple guidelines).
You'll need to check with the author of the app.
