### ISSUE TITLE
Closing a websocket in one coroutine throws error in other coroutine

### ISSUE THREAD

**Issue by jprjr** [daurnimator/lua-http#182]
Hi there, I think this is related to cqueues https://github.com/wahern/cqueues/issues/9

I have an application where I'm reading from a websocket in a coroutine, and I want to close the connection down from another.

I thought the websocket would return `nil, closed` or something along those lines, it winds up throwing an error: `calling recv on bad self (socket closed)`

**Comment by daurnimator** [comment]
Could you come up with a minimized test-case?

**Comment by jprjr** [comment]
I'm so sorry, the error was actually elsewhere (handling a UDP connection), I'll close this.
