### ISSUE TITLE
leading question mark is not ignored by query_args

### ISSUE THREAD

**Issue by Mehgugs** [daurnimator/lua-http#194]
```lua
> for name, value in require"http.util".query_args"?a=b&c=d" do print(name, value) end
?a  b
c   d
```

As far as im aware, you cannot have a ? in a query string without encoding it.

**Comment by daurnimator** [comment]
> As far as im aware, you cannot have a ? in a query string without encoding it.

You can.
See RFC 3986:
`query         = *( pchar / "/" / "?" )`
i.e. a query can be made up of any path character, `/`, or `?`.

----

The string you pass to `query_args` should be the query string, not the query string with a leading `?`.
