### ISSUE TITLE
server_hello.lua

### ISSUE THREAD

**Issue by Vincent-vst** [daurnimator/lua-http#205]
I can't seem to run server_hello.lua in the example folder.   
```bash
$ lua server.lua 8888
lua: server.lua:56: The name does not resolve for the supplied parameters
stack traceback:
	[C]: in function 'assert'
	server.lua:56: in main chunk
	[C]: in ?
```
same with no parameters   
```bash
lua server.lua
lua: server.lua:56: The name does not resolve for the supplied parameters
stack traceback:
	[C]: in function 'assert'
	server.lua:56: in main chunk
	[C]: in ?
```  
I don't know what am I doing wrong

**Comment by daurnimator** [comment]
> I don't know what am I doing wrong

https://github.com/daurnimator/lua-http/blob/169c1a7586d39be1bf0d98b69934e8e8b08a87cd/examples/server_hello.lua#L43

I would expect the issue is that your local DNS resolver doesn't return anything for `localhost`

**Comment by Vincent-vst** [comment]
Yup, you were right, I replaced it with 127.0.0.1 and it's now working ! Thank you
