### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by zxz970104** [daurnimator/lua-http#206]
lua examples/simple_request.lua https://www.baidu.com/

# REQUEST
## HEADERS
:method	GET
:authority	www.baidu.com
:path	/
:scheme	https
user-agent	lua-http/scm

# RESPONSE
starttls: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:unable to get local issuer certificate

How can I fix it

**Comment by zxz970104** [comment]
and another question :  How can I get an image from https and save it

**Comment by daurnimator** [comment]
> starttls: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:unable to get local issuer certificate

This likely means the certificate authority is not installed on your computer
e.g. because:
  - you don't have the ca cert
  - you're behind a man-in-the middle

**Comment by daurnimator** [comment]
Closing due to lack of information+inactivity.
