### ISSUE TITLE
Is connection pool being used in lua-http v0.4

### ISSUE THREAD

**Issue by Yash-Bhange** [daurnimator/lua-http#227]
Hi @daurnimator , 

quick query : Just wanted to know that if connection pool is being used in lua-http v0.4 version?

I am not able to find the answer for above question on internet. Also if it there how can i know if my connection is being reused?

**Comment by daurnimator** [comment]
Not right now. See https://github.com/daurnimator/lua-http/issues/10

**Comment by YashBhange-Druva** [comment]
Hello @daurnimator , Thanks for the quick response.

If i set http version=1 in option and use connection=keep-alive header then will it be used?
