### ISSUE TITLE
Read proxy from environmental variables

### ISSUE THREAD

**Issue by daurnimator** [daurnimator/lua-http#23]
Many users require use of a http proxy to make requests outside of their local network.
Provide a way to pick up common environmental variables that specify proxies.

From curl:
> The lower case version has precedence. http_proxy is an exception as it is only available in lower case.

  - [x] `http_proxy`: Sets the proxy server to use for HTTP.
  - [x] `HTTPS_PROXY`: Sets the proxy server to use for HTTPS.
  - [x] `ALL_PROXY`: Sets the proxy server to use if no protocol-specific proxy is set.
  - [x] `NO_PROXY`: list of host names that shouldn't go through any proxy. If set to a asterisk '*' only, it matches all hosts.

See also:
  - [curl](https://curl.haxx.se/docs/manpage.html#ENVIRONMENT)
  - [wget](https://www.gnu.org/software/wget/manual/html_node/Proxies.html#Proxies)

**Comment by dominics** [comment]
See also: httpoxy.org

If you do implement the read of `http_proxy` (the lower-case form), you must also assert case-sensitive environment variables are in use (does not seem to be the case on windows, although I haven't checked lua's os.getenv specifically).

Even so, a nice feature would be to match Ruby, libwww-perl, etc. and honor `CGI_HTTP_PROXY` in the presence of CGI, which you can detect via `REQUEST_METHOD` or similar (it has the advantage of being a 'safer' mitigation; application authors are more likely to use that method if they really do need to configure a proxy under CGI).

**Comment by daurnimator** [comment]
> honor CGI_HTTP_PROXY in the presence of CGI, which you can detect via REQUEST_METHOD or similar

So what would the logic for this be?
if the environmental variable `REQUEST_METHOD` is defined, look at `CGI_HTTP_PROXY` instead?
I guess this doesn't apply to HTTPS_PROXY, ALL_PROXY or NO_PROXY, as they don't have the magic CGI `HTTP_` prefix?
