### ISSUE TITLE
Install with Luarocks doesn't work.

### ISSUE THREAD

**Issue by ner0x652** [daurnimator/lua-http#24]
Using `luarocks install --server=http://luarocks.org/dev http` results in `Error: Unknown protocol git+https`.

OS: Debian 8
luarocks 2.2.0

I guess it is somehow related to this https://github.com/daurnimator/lua-http/blob/master/http-scm-0.rockspec#L11 .

**Comment by daurnimator** [comment]
This is a known issue with luarocks 2.2.0.
Please upgrade to at least luarocks 2.2.2.

Btw, this is only an issue for the development rockspec of lua-http.
I real release will work fine with older luarocks version.
