### ISSUE TITLE
lbase64 for Lua 5.0-5.2, not 5.3

### ISSUE THREAD

**Issue by ChickenNuggers** [daurnimator/lua-http#3]
Can we use a Lua 5.3-compatible fork of lbase64 or use something else? If not, could we include installation instructions for Lua 5.3 compatibility?

**Comment by daurnimator** [comment]
lbase64 *is* 5.3 compatible... see e.g. https://luarocks.org/manifests/ignacio/lbase64-20120807-3.rockspec

But, I was actually going to change over to [basexx](https://github.com/aiq/basexx) for other reasons. Perhaps I should do that sooner rather than later?

**Comment by ChickenNuggers** [comment]
The links provided on the website did not mention a Lua 5.3-compatible version, which is why I was concerned.

**Comment by daurnimator** [comment]
> The links provided on the website did not mention a Lua 5.3-compatible version, which is why I was concerned.

Quoting Luiz (private mail):
> I haven't released an lbase64 tarball for Lua 5.3, mostly because the code
> code is the same; the only differences are in the Makefile because Lua 5.3
> insists on a C99 compiler. Perhaps I should release a tarball...

I sent him a link to this thread.

**Comment by ChickenNuggers** [comment]
Thanks. There's not much of a note that they're the same, so it would also be nice to state that somewhere, unless I skimmed over it (which is completely possible).

**Comment by daurnimator** [comment]
Luiz just added a 5.3 link to http://www.tecgraf.puc-rio.br/~lhf/ftp/lua/#lbase64
