### ISSUE TITLE
cqueues and luaossl rockspecs ignore LDFLAGS, broken on OS X

### ISSUE THREAD

**Issue by vavrusa** [daurnimator/lua-http#34]
Couldn't find the project dedicated to luaossl/cqueues rockspec dependencies, apologies if this is the wrong place.

## Problem

The rockspecs for luaossl/cqueues link against different openssl version on OS X.

## Why

OS X since El Capitan doesn't ship OpenSSL headers, so they have to be installed separately.
The rockspec accepts `OPENSSL_DIR` and `CRYPTO_DIR` variables to set CFLAGS/LDFLAGS, but the [rockspec](https://luarocks.org/manifests/daurnimator/cqueues-20160316.51-0.rockspec) sets CFLAGS only. As a result, it is built with mismatching header/library version and crashes.

### How to reproduce

*(Same thing for cqueues/openssl)*

```bash
$ cd cloned_cqueues
$ make CC=cc CFLAGS=-I/usr/local/opt/openssl/include
$ otool -L src/5.1/cqueues.so
src/5.1/cqueues.so:
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
```

### How to build it right

```bash
$ make CC=cc CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS="-L/usr/local/opt/openssl/lib"
$ otool -L src/5.1/cqueues.so
src/5.1/cqueues.so:
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by daurnimator** [comment]
It's mentioned over here: https://github.com/wahern/cqueues/wiki/Installation-on-OSX#via-brew

Is there something you think lua-http should/can do here?

**Comment by vavrusa** [comment]
That doesn't work because the luaossl/cqueues rockspec passes along only the CFLAGS and not LDFLAGS. It would work if you passed along LDFLAGS just like you pass along CFLAGS [here](https://luarocks.org/manifests/daurnimator/cqueues-20160316.51-0.rockspec):

```
	build_variables = {
		CFLAGS = "$(CFLAGS)";
		LDFLAGS = "$(LDFLAGS)"; -- ADDED
		bindir = "$(LUA_BINDIR)";
		includedir = "$(LUA_INCDIR)";
		libdir = "$(LUA_LIBDIR)";
	};
```

I mean... right now it's going to compile, install and somehow work, but then it's going to crash on some function calls that openssl 0.9.8 doesn't implement or has different ABI.
Does it make sense?

**Comment by daurnimator** [comment]
> That doesn't work because the luaossl/cqueues rockspec passes along only the CFLAGS and not LDFLAGS.

IIRC luarocks passes all variables on command line through to make.
CFLAGS needs a special mention in `build_variables` because it tries to assemble it from `OPENSSL_INCDIR` and such.

**Comment by vavrusa** [comment]
Not really.

```bash
$ luarocks-5.1 install cqueues CC=cc LDFLAGS=-L/usr/local/opt/openssl/lib CPPFLAGS=-I/usr/local/opt/openssl/include
Installing https://luarocks.org/cqueues-20160316.51-0.src.rock...
Using https://luarocks.org/cqueues-20160316.51-0.src.rock... switching to 'build' mode
Error: Could not find header file for CRYPTO
  No file openssl/crypto.h in /usr/local/include
  No file openssl/crypto.h in /usr/include
You may have to install CRYPTO in your system and/or pass CRYPTO_DIR or CRYPTO_INCDIR to the luarocks command.
Example: luarocks install cqueues CRYPTO_DIR=/usr/local

$ luarocks-5.1 install cqueues CC=cc LDFLAGS=-L/usr/local/opt/openssl/lib CFLAGS=-I/usr/local/opt/openssl/include CRYPTO_DIR=/usr/local/opt/openssl
Installing https://luarocks.org/cqueues-20160316.51-0.src.rock...
Using https://luarocks.org/cqueues-20160316.51-0.src.rock... switching to 'build' mode
Error: Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install cqueues OPENSSL_DIR=/usr/local

$ luarocks-5.1 install cqueues CC=cc LDFLAGS=-L/usr/local/opt/openssl/lib CFLAGS=-I/usr/local/opt/openssl/include CRYPTO_DIR=/usr/local/opt/openssl OPENSSL_DIR=/usr/local/opt/openssl
Installing https://luarocks.org/cqueues-20160316.51-0.src.rock...
... snip ...
cc -o ... object files ...  -bundle -undefined dynamic_lookup   -L/usr/local/lib -L/usr/local/lib -lssl -lcrypto -lpthread -ldl -lm 
... snip ...
Updating manifest for /usr/local/lib/luarocks/rocks-5.1
cqueues 20160316.51-0 is now built and installed in /usr/local (license: MIT/X11)

$ otool -L /usr/local/lib/lua/5.1/_cqueues.so
/usr/local/lib/lua/5.1/_cqueues.so:
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

The LDFLAGS is not honored in the build (it's missing altogether during linking) and the cqueues is built with a wrong library.

**Comment by daurnimator** [comment]
hmmm. I remember there being some issue with `LDFLAGS` in luarocks.... 

In that case, could the recommendation just be to run `brew link openssl --force`?

**Comment by vavrusa** [comment]
It's probably a good recommendation but at the same time it might break other packages.
I'd rather support LDFLAGS well (luasec build fine for example) and recommend forced openssl linking than requiring openssl to be force-linked.

**Comment by daurnimator** [comment]
I've added LDFLAGS to the cqueues rockspec now.

For luaossl I can't though: it uses the 'builtin' luarocks built type.
