### ISSUE TITLE
Start making releases

### ISSUE THREAD

**Issue by jirutka** [daurnimator/lua-http#36]
Could you please start making releases (git tags and LuaRocks)? I’d like to make an Alpine package for this module, but it’s kinda problematic to make a package for something that doesn’t have any version number.

**Comment by daurnimator** [comment]
Yeah I should :D I'm mainly waiting for a cqueues release right now that lua-http needs to avoid leaks in 5.1 + luajit.
I also need to make an lpeg_patterns release so I can merge some PRs here.

I've created a github milestone to track: https://github.com/daurnimator/lua-http/milestones/First%20release

**Comment by torhve** [comment]
+1 Would also like this!

**Comment by daurnimator** [comment]
Okay, now I have no excuses!
Will try and cut a release tomorrow.

**Comment by daurnimator** [comment]
sorry, I've been slack on this. Still meaning to do it.

**Comment by jirutka** [comment]
gentle reminder 🐱

**Comment by daurnimator** [comment]
Thought I'd broken something and spent the night tracking down what ended up being only a cqueues issue (https://github.com/wahern/cqueues/issues/161).

We'll get there :)

**Comment by jirutka** [comment]
End of the year is approaching and still no release. 😿

**Comment by ChickenNuggers** [comment]
Totally not my fault for not working on HSTS. :stuck_out_tongue:

**Comment by daurnimator** [comment]
Sorry :( anyone got last issues to mention before release? Can everyone do a quick set of tests with HEAD to make sure I haven't broken anything?

Also if anyone wants to help write docs.

**Comment by daurnimator** [comment]
> Totally not my fault for not working on HSTS. :stuck_out_tongue:

HSTS was merged (I wrote it on the plane :P)

> Also if anyone wants to help write docs.

Big shout out to @RussellHaley helping with docs in #49 

> make sure I haven't broken anything

I have merged in TLS peer verification by default (#48): I expect more possible breakages, especially as I had to hard-code in a path (`/etc/ssl/certs`) until luaossl gets an update.

**Comment by ChickenNuggers** [comment]
> I had to hard-code in a path

I don't suppose you can provide a method to change the path until the luaossl update?

**Comment by daurnimator** [comment]
Here we are again: I think I'm ready for a release now.
If nothing comes up between now and tomorrow I'll do it!

**Comment by daurnimator** [comment]
Done! https://github.com/daurnimator/lua-http/releases/tag/v0.1
