### ISSUE TITLE
luaossl build fails on FreeBSD 11 rc2

### ISSUE THREAD

**Issue by RussellHaley** [daurnimator/lua-http#40]
http://pastebin.com/vXPkwFiS

Linker problem? I think I had to take a -ldl out of something else I was building once. I don't know where luarocks puts the source so I can't check the makefile. The makefile from wahern is pretty advanced for me, I couldn't find any linker flags.

**Comment by daurnimator** [comment]
(Should probably have filed this with luaossl or just emailed me; it's not a lua-http issue)

> Linker problem? I think I had to take a -ldl out of something else I was building once

Looks like freebsd doesn't want `-ldl`

> I don't know where luarocks puts the source so I can't check the makefile

The luaossl rock doesn't use a makefile; it uses the luarocks built in build rules

I'll update the rockspec now :)

**Comment by daurnimator** [comment]
http://luarocks.org/modules/daurnimator/luaossl/20151221-1 is now uploaded.
