### ISSUE TITLE
Streaming doesn't work in my particular case.

### ISSUE THREAD

**Issue by ziazon** [daurnimator/lua-http#46]
I'm following one of your examples for the http streaming (shown here) with only a few things changed... url and variable names:
```
--[[
Makes a request to an HTTP2 endpoint that has an infinite length response.
Usage: lua examples/h2_streaming.lua
]]

local request = require "http.request"

-- This endpoint returns a never-ending stream of chunks containing the current time
local req = request.new_from_uri("https://http2.golang.org/clockstream")
local _, stream = assert(req:go())
for chunk in stream:each_chunk() do
	io.write(chunk)
end
```

It was working great up until about this weekend, now whenever I call this, it only returns one chunk and stops. I run the example code with the example url and it works. I have no idea what's going on as I have not changed a single thing in my API (serves the stream). Nor have I changed my code...

Currently my code is this:
```
local request = require "http.request"

local channelHokuyo = love.thread.getChannel("channelHokuyo")

local streamHokuyo = request.new_from_uri("http://localhost:5000/hokuyo_stream")
local _, stream = assert(streamHokuyo:go())
for chunk in stream:each_chunk() do
    channelHokuyo:push(chunk)
end
```

What I expect is an endless stream of this:
[stream_output.txt](https://github.com/daurnimator/lua-http/files/543566/stream_output.txt)

However, I only get one chunk. Like I said before, it used to work.

Any help would be great!

Note: I am using Love2D and this code is in a seperate thread. But when I isolate the code and run it with lua5.1 as it's own program, it still does the same thing.

**Comment by ziazon** [comment]
As you requested, here you go:

```
:status: 200
content-type: text/event-stream; charset=utf-8
connection: close
server: Werkzeug/0.11.11 Python/3.5.2
date: Sat, 22 Oct 2016 13:21:15 GMT
```

So at this point it's my server?

**Comment by daurnimator** [comment]
Tracked it down. Was a bug introduced by 7701a047eee223da791fba8c6db0694fe431e1e4

**Comment by ziazon** [comment]
Thanks, that worked!
