### ISSUE TITLE
Cookie Management

### ISSUE THREAD

**Issue by daurnimator** [daurnimator/lua-http#6]
-  [ ] `Set-Cookie` parsing (https://tools.ietf.org/html/rfc6265#section-5.2)
-  [ ] utility function to create Set-Cookie headers (https://tools.ietf.org/html/rfc6265#section-4)
-  [ ] "cookie jar" data structure for clients (follow https://tools.ietf.org/html/rfc6265#section-5.3)
-  [ ] `Cookie` header creation (follow https://tools.ietf.org/html/rfc6265#section-5.4)

I'm happy for this to use either lpeg or plain lua patterns.

**Comment by daurnimator** [comment]
> Set-Cookie parsing (https://tools.ietf.org/html/rfc6265#section-5.2)

There is a Set-Cookie parser in https://github.com/daurnimator/lpeg_patterns/pull/2/files

**Comment by daurnimator** [comment]
Added a commit to lpeg_patterns to fix cookie parsing: https://github.com/daurnimator/lpeg_patterns/commit/b124aa096f757b856fc4f9e5a79cc5f00bbb84b9

Will need new lpeg_patterns release.

**Comment by daurnimator** [comment]
Today I wrote https://github.com/daurnimator/lua-psl which might be useful.

**Comment by vkill** [comment]
There is a create Set-Cookie in https://github.com/cloudflare/lua-resty-cookie/blob/v0.1.0/lib/resty/cookie.lua#L136

**Comment by RyanSquared** [comment]
Not to be rude against the authors, but I'm not really up for adding code that looks like https://github.com/cloudflare/lua-resty-cookie/blob/v0.1.0/lib/resty/cookie.lua#L144-L151. A much better way to do it would be using `table.concat` and populating a table instead; this involves a lot of checks and concatenation.

**Comment by daurnimator** [comment]
> A much better way to do it would be using table.concat and populating a table instead; this involves a lot of checks and concatenation.

@RyanSquared why so? the concat operator is rather fast when you do it all at once. It even optimises for the empty string

**Comment by RyanSquared** [comment]
> It even optimises for the empty string

That I was not aware of. However, I do recall using `table.concat()` being faster in at least one case, and that's what I've usually used.

Does the resulting code only have one `OP_CONCAT`? If so, that's good, but I thought that doing large amounts of concatenation was considered slow. I'd be happy to be proven wrong though.

**Comment by daurnimator** [comment]
> However, I do recall using table.concat() being faster in at least one case, and that's what I've usually used.

`table.concat` is preferred if you are do concatenation in a loop where you don't know the total number of elements beforehand

> Does the resulting code only have one OP_CONCAT? If so, that's good, but I thought that doing large amounts of concatenation was considered slow. I'd be happy to be proven wrong though.

It should. And `table.concat` internally uses the exact same internal C function as OP_CONCAT, so it wouldn't be any different (and infact it'll be worse).

**Comment by RyanSquared** [comment]
> and infact it'll be worse

Right, because you're doing allocations as well as the `OP_CONCAT` stuff. Got it.

Note for reference: future `http.cookies` module is where relevant methods will be stored
