### ISSUE TITLE
Upsert Content-Type header causes error in http2 & https websites

### ISSUE THREAD

**Issue by Whitecl4ws** [daurnimator/lua-http#66]
Tried with multiple https/http2 websites, including http2.golang.org and my own website
```
package.path = package.path .. ";./libs/?.lua;./libs/?/init.lua"
package.cpath = package.cpath .. ";./libs/?.so"
local request = require "http.request"

-- This endpoint returns a never-ending stream of chunks containing the current time
local req = request.new_from_uri("https://web.site/login")
req.headers:upsert(":method", "POST")
req.headers:upsert("Content-Type", "application/x-www-form-urlencoded") <-- Adding this makes the example crash
req:set_body("Name=Bla&LastName=Bla")
local _, stream = assert(req:go())
local body, err = stream:get_body_as_string()
print(body)

```
How I fixed this is by appending the header server-side and the reason I needed the header:
http://stackoverflow.com/questions/39122458/get-post-data-using-golang-http-package

**Comment by daurnimator** [comment]
> req.headers:upsert("Content-Type", "application/x-www-form-urlencoded") <-- Adding this makes the example crash

You you use lower case headers fields. i.e. `req.headers:upsert("content-type", "application/x-www-form-urlencoded")`
It appears that if it's not lower case go's http library will reject the http request without even logging a debug message.

**Comment by daurnimator** [comment]
Looking at HTTP2 spec, this is meant to be a malformedness error, from section 8.1.2:

> Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion. However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed 

I should add this check into lua-http's server component.

**Comment by daurnimator** [comment]
@Whitecl4ws did that answer your issue?

**Comment by Whitecl4ws** [comment]
Well I fixed it server-side but I guess that works too
