### ISSUE TITLE
Timeout convention could do with documenting

### ISSUE THREAD

**Issue by kinnison** [daurnimator/lua-http#76]
Many functions take a timeout; but only a few have the format of the timeout documented.

It'd be nice if this were covered in the conventions (then those few functions which mention seconds can be also be cleaned up)

Super-nice would be if every timeout argument in a function description were a link to that convention, though I appreciate that might be harder to do.

**Comment by daurnimator** [comment]
To clarify: yes, all `timeout` arguments take seconds.

**Comment by daurnimator** [comment]
```
## Timeouts

All operations that may block the current thread take a `timeout` argument.
This argument is always the number of seconds to allow before returning with errno set to `ETIMEDOUT`.
```

Would that be enough?

**Comment by kinnison** [comment]
Short, and sweet. Yes, looks good

On 26 October 2017 07:36:14 BST, daurnimator <notifications@github.com> wrote:
>```
>## Timeouts
>
>All operations that may block the current thread take a `timeout`
>argument.
>This argument is always the number of seconds to allow before returning
>with errno set to `ETIMEDOUT`.
>```
>
>Would that be enough?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/daurnimator/lua-http/issues/76#issuecomment-339566115

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
