### ISSUE TITLE
Use Transfer-Encoding: chunked when request body is a function

### ISSUE THREAD

**Issue by tibboh** [daurnimator/lua-http#86]
If a client does `request:set_body(my_generator_function)` lua-http produces a 100-continue probe with neither `Content-Length` nor `Transfer-Encoding: chunked`, and that gets rejected by all servers I've tried.

I would skip the probe if size of the body is not known and switch to chunked encoding.

**Comment by RyanSquared** [comment]
Interesting. There's nothing in the documentation that references this functionality, other than that the function should return chunks in the form of strings (until `nil`), which I thought would've been piped into a table and then sent as a full chunk.

**Comment by tibboh** [comment]
I suppose the goal was to enable efficient streaming for generated content,
where the size is not known in advance and we want to avoid buffering.

10 lis 2017 15:42 "Ryan" <notifications@github.com> napisał(a):

**Comment by daurnimator** [comment]
`Transfer-encoding: chunked` should be added automatically by h1_stream when required https://github.com/daurnimator/lua-http/blob/master/http/h1_stream.lua#L682-L688

Could you paste an example and/or your socket logs? (run with the env var SOCKET_DEBUG=1)

**Comment by tibboh** [comment]
I misread the packet dump, Transfer-Encoding is indeed there. Two servers I tried (httpbin.org and something else) rejected my POST request and I mistakenly assumed this was because of the 100-continue probe.
