### ISSUE TITLE
Tests hanging on Alpine Linux ppc64le (LXC container)

### ISSUE THREAD

**Issue by rgdoliveira** [daurnimator/lua-http#87]
I'm trying to run lua-http 0.2 tests on Alpine Linux 3.6 (ppc64le architecture) and the tests are getting stuck (could not find any log error or something like that). I tried it with lua5.1, 5.2, 5.3 and luajit and got the same behaviour.

I'm running tests using:
$ lua5.1 /usr/bin/busted

In an Alpine Linux x86_64 all tests passed.

For more information, the lua-http build script for Alpine is [here](https://github.com/alpinelinux/aports/blob/master/community/lua-http/APKBUILD)

**Comment by daurnimator** [comment]
I suspect you're running into https://github.com/wahern/cqueues/issues/156

**Comment by rgdoliveira** [comment]
@daurnimator hmm, I don't think that's the case here. The test have been running for hours in Alpine ppc64le builder and they didn't finish.

**Comment by daurnimator** [comment]
In that case we should try and narrow things down a bit. Which test is it getting to?
You can narrow it down to a file by passing the individual files in spec/ to busted.
e.g. `busted spec/h1_connection_spec.lua`.

FWIW the issue i mentioned above happens during a test in spec/compat_socket_spec.lua

**Comment by rgdoliveira** [comment]
The tests that are hanging in my environment (Alpine ppc64le LXC container) are:
- compat_prosody_spec.lua
- compat_socket_spec.lua 
- request_spec.lua 
- server_spec.lua 
- websocket_spec.lua

I tried to build lua-http in Alpine ppc64le VM (in another machine from the LXC container) and all tests passed. Maybe some thing is missing in my environment or an issue the LXC container configuration.

**Comment by daurnimator** [comment]
Hrm, could you let me know the exact test in request_spec.lua it hangs on?
Try using an busted output handler that doesn't buffer. e.g. `busted -o TAP spec/request_spec.lua`

**Comment by rgdoliveira** [comment]
$ lua5.1 /usr/bin/busted -o TAP spec/request_spec.lua
ok 1 - http.request module can construct a request from a uri
ok 2 - http.request module can construct a request with custom proxies object
ok 3 - http.request module can construct a CONNECT request
ok 4 - http.request module fails on invalid URIs
ok 5 - http.request module can (sometimes) roundtrip via :to_uri()
ok 6 - http.request module :to_uri() throws on un-coerable authorization
ok 7 - http.request module handles CONNECT requests in :to_uri()
ok 8 - http.request module :set_body sets content-length for string arguments
ok 9 - http.request module :set_body sets expect 100-continue for file arguments
ok 10 - http.request module :handle_redirect method works
ok 11 - http.request module :handle_redirect method works with cross-scheme port-less uri
ok 12 - http.request module :handle_redirect method works with scheme relative uri with just domain
ok 13 - http.request module :handle_redirect method works with scheme relative uri
ok 14 - http.request module :handle_redirect method adds authorization headers for redirects with userinfo
ok 15 - http.request module :handle_redirect method simplifies relative paths
ok 16 - http.request module :handle_redirect method rejects relative redirects when base is invalid
ok 17 - http.request module :handle_redirect method works with query in uri
ok 18 - http.request module :handle_redirect method detects maximum redirects exceeded
ok 19 - http.request module :handle_redirect method detects missing location header
ok 20 - http.request module :handle_redirect method detects invalid location header
ok 21 - http.request module :handle_redirect method fails on unknown scheme
ok 22 - http.request module :handle_redirect method detects POST => GET transformation
ok 23 - http.request module :handle_redirect method deletes keeps original custom host, port and sendname if relative
ok 24 - http.request module :handle_redirect method removes referer header on https => http redirect
ok 25 - http.request module :handle_redirect method doesn't attach userinfo to referer header
ok 26 - http.request module :handle_redirect method works with CONNECT requests
ok 27 - http.request module :handle_redirect method rejects invalid CONNECT redirects

**Comment by daurnimator** [comment]
So it's failing on the first `:go method` test.

Does this work for you?:
```
lua5.1 -e 'print(assert(require"cqueues.socket".listen{host="localhost",port=0}):listen(5))'
```

**Comment by rgdoliveira** [comment]
In Alpine LXC container (where tests hang) shows:
$ lua5.1 -e 'print(assert(require"cqueues.socket".listen{host="localhost",port=0}):listen(5))'
nil	110

In Alpine VM (where tests work) shows:
$ lua5.1 -e 'print(assert(require"cqueues.socket".listen{host="localhost",port=0}):listen(5))'
userdata: 0x10006006bc8

**Comment by daurnimator** [comment]
Could you run it under `strace` so we can see what's happening?

What is your DNS setup in the LXC container? How does that compare to where things work?

**Comment by rgdoliveira** [comment]
The strace log is here : http://tpaste.us/ZVw9


-  Seems it worked using 127.0.0.1, see:
$ lua5.1 -e 'print(assert(require"cqueues.socket".listen{host="127.0.0.1",port=0}):listen(5))'
userdata: 0x1002be06bc8

- Regarding DNS:
The dns of LXC container:
$ cat /etc/resolv.conf 
nameserver 172.21.5.1

The dns of the VM:
$ cat /etc/resolv.conf 
nameserver 10.1.0.1

**Comment by ncopa** [comment]
could it be that it resolves `localhost` to an ipv6 address, while ipv6 is not properly confiugred.

**Comment by daurnimator** [comment]
Looking at your `strace` result,
The query is sent:
```
connect(6, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.21.5.1")}, 16) = 0
sendto(6, "ys\1\0\0\1\0\0\0\0\0\0\tlocalhost\0\0\0\1\0\1", 28, 0, NULL, 0) = 28
```
But there is no reply from your dns server.

This suggests a local misconfiguration?

**Comment by daurnimator** [comment]
> `sendto(6, "ys\1\0\0\1\0\0\0\0\0\0\tlocalhost\0\0\0\1\0\1", 28, 0, NULL, 0) = 28`

huh. this dns packet isn't right. decoded:
```json
{ id: 31091,
  type: 'query',
  flags: 256,
  questions: [ { name: 'localhost', type: 'UNKNOWN_0', class: 256 } ],
  answers: [],
  authorities: [],
  additionals: [] }
```

Which looks very similar to https://github.com/wahern/cqueues/issues/156#issuecomment-340228470

**Comment by richfelker** [comment]
The invalid packet has an extra nul byte between the label and the class/type fields; this is why they appear invalid. I don't see any plausible cause for why this happens, especially only on ppc64le. I wonder if it's a codegen bug in the compiler...

**Comment by richfelker** [comment]
Actually, if it's calling connect at all, that means it's not using the libc resolver; musl does not use connect. So there must be some other code doing its own dns query...

**Comment by daurnimator** [comment]
> Actually, if it's calling connect at all, that means it's not using the libc resolver; musl does not use connect. So there must be some other code doing its own dns query...

Correct. This project uses cqueues which embeds https://github.com/wahern/dns

**Comment by daurnimator** [comment]
@ncopa on IRC you mentioned you'd have a look into this: I don't suppose you've had some free cycles?

**Comment by ncopa** [comment]
@daurnimator um, I have sort of forgotten it (and been on vacation). sorry

**Comment by daurnimator** [comment]
Issue discovered and PR sent upstream. Closing this issue.

**Comment by rgdoliveira** [comment]
@daurnimator could you please add the link of the PR that fixes this problem?

**Comment by daurnimator** [comment]
See https://github.com/wahern/cqueues/issues/156#issuecomment-397834837
