### ISSUE TITLE
Trying to compile on windows fails due to missing crypto

### ISSUE THREAD

**Issue by thegrb93** [daurnimator/lua-http#92]
https://stackoverflow.com/questions/19321982/libcrypto-equivalent-missing-on-windows

**Comment by thegrb93** [comment]
```
C:\Program Files (x86)\Lua\5.1>luarocks.bat install http CRYPTO_DIR="C:\Program Files (x86)\OpenSSL-Win32"
Installing https://luarocks.org/http-0.2-0.all.rock
Missing dependencies for http 0.2-0:
   cqueues >= 20161214 (not installed)
   luaossl >= 20161208 (not installed)
   basexx >= 0.2.0 (not installed)
   lpeg (not installed)
   lpeg_patterns >= 0.3 (not installed)
   fifo (not installed)

http 0.2-0 depends on cqueues >= 20161214 (not installed)
Installing https://luarocks.org/cqueues-20171014.51-0.src.rock

Error: Failed installing dependency: https://luarocks.org/cqueues-20171014.51-0.src.rock - Could not find library file for CRYPTO
  No file crypto.lib in C:\Program Files (x86)\OpenSSL-Win32/lib
  No file crypto.dll in C:\Program Files (x86)\OpenSSL-Win32/lib
  No file libcrypto.dll in C:\Program Files (x86)\OpenSSL-Win32/lib
You may have to install CRYPTO in your system and/or pass CRYPTO_DIR or CRYPTO_LIBDIR to the luarocks command.
Example: luarocks install cqueues CRYPTO_DIR=/usr/local
```

**Comment by thegrb93** [comment]
Just realized this is a cqueues issue. I'll go search for support for that.

**Comment by thegrb93** [comment]
Apparently the author intentionally does not support windows.

**Comment by rokf** [comment]
The library wouldn't be the same without `cqueues`. Quote from the website:

> The concept is not portable to Windows because Windows lacks an analog to the pollable event queues of modern Unix systems. Libraries which try to abstract the two approaches—event readiness signaling versus event completion—invariably produce a pallid least common denominator library suffering all the weaknesses and enjoying none of the strengths of each approach.

**Comment by thegrb93** [comment]
I'll look into the luasec library perhaps.

**Comment by RussellHaley** [comment]
Perhaps have a look at luvit?

**Comment by thegrb93** [comment]
Thanks for the suggestion. I think that may work.
