### ISSUE TITLE
Sailor Project: in search of a Lua 5.3 production server

### ISSUE THREAD

**Issue by CodelessFuture** [daurnimator/lua-http#93]
Hi. I'm Massimiliano Bertinetti and I'm helping Etienne Dalcol maintaining Sailor.

I'm on a disperate search of a way of putting in production Sailor with Lua 5.3, so that any progress on the framework can point on the last language version.

I actually use Xavante, not the version on Luarocks but the master repo. I see you propose to rewrite Pegasus to support Lua-http: can we join force toward the objective of a Lua 5.3 Web Server?
I make the same request to @EvandroLG

**Comment by daurnimator** [comment]
I replied on your issues at https://github.com/EvandroLG/pegasus.lua/issues/100

Go for it: let me know what you need.
