### ISSUE TITLE
TechEmpower comparison

### ISSUE THREAD

**Issue by aleclarson** [daurnimator/lua-http#94]
How does `lua-http` compare in the TechEmpower benchmarks?

https://www.techempower.com/benchmarks

**Comment by daurnimator** [comment]
lua-http is a library that should be used to *write* a http server/framework; it is not a server itself.
This isn't a category that fits into the linked benchmarks.

**Comment by aleclarson** [comment]
@daurnimator Okay, but you could use the example server for the benchmarks.

**Comment by daurnimator** [comment]
> you could use the example server for the benchmarks.

The example server is not built for speed: only to be a simple server example (though I think it's reasonable fast...)

A faster implementation could use threads; and it would move logging off the hot path.

**Comment by aleclarson** [comment]
Good to know. Something in the wiki about performance recommendations would be awesome!

**Comment by daurnimator** [comment]
> But I'm curious how lua-http performs in the JSON benchmark, for example.

90% of the performance there would be based on the json library you select (which lua-http doesn't mandate): you'd essentially be benchmarking e.g. `cjson`.
