### ISSUE TITLE
Non-blocking mode

### ISSUE THREAD

**Issue by aleclarson** [daurnimator/lua-http#95]
`server:loop` blocks its thread, right? Is there a recommended timeout for yielding to other routines? I'm using this on a Tarantool server, so I would be working with fibers, unless you have another suggestion.

**Comment by RyanSquared** [comment]
you can pass a custom cqueues controller and manually step through that with your own timeout. from the [docs][1]: `.cq (cqueue): A cqueues controller to use as a main loop. The default is a new controller for the server.`.

As a quick example:

```moon
cqueues = require "cqueues"
http = server: require "http"

controller = cqueues.new!
server = http.server.new cq: controller

-- do your stuff with `server`

while not cqueues\empty!
    cqueues\loop 1/20 -- do a tiny bit of processing
```

[1]: https://daurnimator.github.io/lua-http/0.2/#http.server.new

**Comment by aleclarson** [comment]
The server instance has `empty` and `loop` methods, so you don't need to create your own `cqueues` controller to do what you suggest.

Regardless, I still don't understand how to use cqueues in harmony with Tarantool fibers. Is there anything important I should know?

Is it recommended to wrap every request (and/or the server loop) with a fiber? Or should I be using the `wrap` method provided by `cqueues`?

I can't find much guidance from Google searches, so I would appreciate any wisdom you have on the subject.

**Comment by aleclarson** [comment]
Found this in the docs:

> Each client request triggers onstream which is called from an independent cqueue, providing an independent process for each request.

I assume that means wrapping each request with `fiber.create` would be overkill.

**Comment by aleclarson** [comment]
This is my current attempt:

```moon
server = http_server.listen opts

fiber.create ->

  -- Expose the server.
  assert server\listen!
  port = select 3, server\localname!
  print 'Listening on port ' .. port
  fiber.yield!

  -- Respond to inbound requests.
  while true
    ok, err = server\step 0
    assert io.stderr\write err, '\n' unless ok
    fiber.yield!
```

But I'm getting ECONNREFUSED when trying to `curl` the address (`http://localhost:50204`).

**Comment by daurnimator** [comment]
Is that moonscript?

You cannot just use Tarantool's `fibre.yield` without specifying what to yield for.
However, tarantool added [`socket.iowait`](https://tarantool.org/en/doc/1.7/reference/reference_lua/socket.html#socket-iowait) for using things like lua-http: it allows you to yield a file descriptor, events and timeout. You can get these from `server:pollfd()`, `server:events()` and `server:timeout()` respecitively.

Alternatively, as @RyanSquared mentioned, you can pass your own `cq` object into the `http.server` constructor; and use that with `socket.iowait`. See https://gist.github.com/daurnimator/c5a71215daaf4327e8f7ef9c620e6315 for an example of that (but with websockets)

**Comment by aleclarson** [comment]
> Is that moonscript?

Yup!

> You cannot just use Tarantool's fibre.yield without specifying what to yield for.

I think you are mistaken. That's never stated in the Tarantool docs.

I hope you can answer some of my other questions in this thread. Thank you!

**Comment by daurnimator** [comment]
> > You cannot just use Tarantool's fibre.yield without specifying what to yield for.
> 
> I think you are mistaken. That's never stated in the Tarantool docs.

Well you *can* use it: but it will just resume the thread the next time through the tarantool mainloop, which is not what I assume you intended.


> > Each client request triggers onstream which is called from an independent cqueue, providing an independent process for each request.

This documentation is misleading: `onstream` is called from an independant coroutine managed by the some cqueues controller. Will fix.

> I assume that means wrapping each request with fiber.create would be overkill.

It would be.

> Is :step or :loop recommended for best per-request performance? Or does it make no difference which I use? Are they both suitable for cooperative multi-tasking?

`:loop` just calls `:step` in a loop.
`:step()` runs each coroutine at maximum *once*. so you might e.g. run `:step(0)` then yield so that other tarantool threads may run. Whereas `:loop` runs for as long as you tell it to.


-----------

I think the best solution would be to wrap `cqueues.poll` in something that checks if it's at the top of the stack, and if so, uses `socket.iowait` instead. This would make the whole thing seamless.

**Comment by daurnimator** [comment]
> I think the best solution would be to wrap cqueues.poll in something that checks if it's at the top of the stack, and if so, uses socket.iowait instead. This would make the whole thing seamless.

See https://gist.github.com/daurnimator/f1c7965b47a5658b88300403645541aa
