### ISSUE TITLE
Detect if request has empty body

### ISSUE THREAD

**Issue by aleclarson** [daurnimator/lua-http#96]
I tried `stream:get_body_chars(1)`, assuming it would return an error if there is no request body.

Instead, I get this:
```
attempt to yield across C-call boundary

0	[C]: in function 'poll'
1	/path/to/cqueues/socket.lua:43: in function 'timed_poll'
2	/path/to/cqueues/socket.lua:550: in function 'read_body_by_length'
3	/path/to/http/h1_stream.lua:857: in function 'get_next_chunk'
4	/path/to/http/stream_common.lua:68: in function 'get_body_chars'
5	./api/json/router.lua:55: in function <./api/json/router.lua:44>
6	[C]: in function 'xpcall'
7	./api/server.lua:71: in function <./api/server.lua:55>
8	[builtin#21]: at 0x01034ec810
```

**Comment by daurnimator** [comment]
This error suggests as issue with [cqueues's lua 5.1 workaround](https://github.com/wahern/cqueues/blob/36b4b8cf1d8d3e3224cab04357dda3a633c7f0ff/src/cqueues.lua#L80-L95) (not lua-http)

Or possibly a `lua_pcall` used somewhere? (which in lua5.1/luajit cannot be yielded over)
> `6	[C]: in function 'xpcall'`

Can you tell me more about that `xpcall`?

**Comment by aleclarson** [comment]
The `xpcall` is used to catch errors thrown by any route handlers.

**Comment by daurnimator** [comment]
Does luajit allow you to yield over an `xpcall`? (I know normal lua 5.1 doesn't)

**Comment by daurnimator** [comment]
> Does luajit allow you to yield over an xpcall? (I know normal lua 5.1 doesn't)

Seems like it does.

```lua
f=coroutine.wrap(function() print(xpcall(function() coroutine.yield("foo") end, debug.traceback)) end)
print(f()) --> foo
```

**Comment by daurnimator** [comment]
I don't suppose tarantool (where I assume you're using this?) has overridden xpcall or something?

**Comment by aleclarson** [comment]
It seems a lying `Content-Length` header was the culprit. But I would expect a more graceful failure. Like `get_body_chars` returning nil and an error message.

**Comment by daurnimator** [comment]
> It seems a lying Content-Length header was the culprit. But I would expect a more graceful failure. Like get_body_chars returning nil and an error message.

That doesn't make a lot of sense: a lying content-length header wouldn't suddenly introduce a new C-call boundary.

**Comment by daurnimator** [comment]
This issue ended up being caused by the semantics of tarantool fibers: they aren't based on coroutines, but C stack swittching. Also, `fiber.create` runs immediately; not later from the main loop.
My lua-http<->tarantool gist has been updated to reflect this. https://gist.github.com/daurnimator/f1c7965b47a5658b88300403645541aa
